name: Build App IPA

on:
  workflow_dispatch:
    inputs:
      spotsplusplus_version:
          description: "The version of SpotC++"
          default: ""
          required: true
          type: string
      bundle_id:
          description: "Modify the bundle ID. Not recommended"
          default: "com.yodaluca23.SpotCPlusPlus"
          required: false
          type: string
      decrypted_spotify_url:
          description: "The direct URL to the decrypted Spotify ipa"
          default: ""
          required: true
          type: string
      spotilife_url:
          description: "The direct URL to the Spotilife Tweak"
          default: ""
          required: true
          type: string
      sposify_url:
          description: "The direct URL to the Sposify Tweak"
          default: ""
          required: true
          type: string
      sposify_fix_url:
          description: "The direct URL to the SposifyFix Tweak"
          default: ""
          required: true
          type: string
      spotify_tweak:
          description: "The direct URL to any other tweaks to be injected"
          default: ""
          required: False
          type: string

jobs:
    build:
      runs-on: macos-latest
      steps:

      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Azule CLI
        run:  |
          git clone https://github.com/Al4ise/Azule ~/Azule
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule
          
      - name: Download IPA and Tweaks
        run:  |
          cd ~/Assets
          curl -o spotifyipa ${{ inputs.decrypted_spotify_url }}
          curl -o spotilifedeb ${{ inputs.spotilife_url }}
          curl -o sposifydeb ${{ inputs.sposify_url }}
          curl -o sposifyfixdeb ${{ inputs.sposify_fix_url }}
          curl -o othertweakdeb ${{ inputs.spotify_tweak }}
          cd ~

      - name: Inject Debs
        run:  azule -n patchedspotifyipa -i ~/Assets/spotifyipa.ipa -o ~ -f ~/Assets/spotilifedeb ~/Assets/sposifydeb ~/Assets/sposifyfixdeb ~/Assets/othertweakdeb -c ${{ inputs.spotsplusplus_version }} -b ${{ inputs.bundle_id }} -e 

      - name: Upload IPA App
        uses: actions/upload-artifact@v3.1.1
        with:
          path: ~/patchedspotifyipa.ipa
